# Generated by Django 3.1.4 on 2020-12-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='multi',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
