# Generated by Django 3.1.4 on 2020-12-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestapi', '0002_users_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pdf_history',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='trialID',
            field=models.TextField(),
        ),
    ]
