# Generated by Django 3.1.4 on 2020-12-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestapi', '0003_auto_20201231_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='edc_time',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='total_edc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
